### ISSUE TITLE
Error with google material design component 

### ISSUE THREAD

**Issue by TarunPal3551** [Ferfalk/SimpleSearchView#17]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.kiranastore, PID: 11561
    java.lang.IncompatibleClassChangeError: Class 'com.ferfalk.simplesearchview.SimpleSearchView$5' does not implement interface 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener' in call to 'void com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener.onTabUnselected(com.google.android.material.tabs.TabLayout$Tab)' (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
        at com.google.android.material.tabs.TabLayout$1.onTabUnselected(TabLayout.java:824)
        at com.google.android.material.tabs.TabLayout.dispatchTabUnselected(TabLayout.java:1796)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1780)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1743)
        at com.google.android.material.tabs.TabLayout$Tab.select(TabLayout.java:2135)
        at com.google.android.material.tabs.TabLayout$TabView.performClick(TabLayout.java:2323)
        at android.view.View$PerformClick.run(View.java:19749)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by NLLAPPS** [comment]
I have this issue to. Has this library abandoned?

**Comment by NLLAPPS** [comment]
I had to import this library as a module and update to androidx as well as version of material components i am using to get around this issues
