### ISSUE TITLE
Turn off Animation completely

### ISSUE THREAD

**Issue by zunjae** [Ferfalk/SimpleSearchView#3]
Unfortunately this library crashes for me on certain devices. I can not reproduce the error myself. 

Here is the crashlog:

Caused by java.lang.IllegalStateException: Cannot start this animator on a detached view!
       at android.view.RenderNode.addAnimator(RenderNode.java:803)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:300)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:282)
       at android.animation.RevealAnimator.(RevealAnimator.java:37)
       at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:71)
       at com.ferfalk.simplesearchview.utils.SimpleAnimationUtils.hideOrFadeOut(Unknown Source:22)
       at com.ferfalk.simplesearchview.SimpleSearchView.closeSearch$1385ff(Unknown Source:25)
       at com.ferfalk.simplesearchview.SimpleSearchView.onSubmitQuery(Unknown Source:27)
       at com.ferfalk.simplesearchview.SimpleSearchView.showSearch(Unknown Source:28)

This happens in the onCreate and only on specific devices.

Any idea how I could fix this issue?

**Comment by zunjae** [comment]
Important thing to note: Yes, I've set the animate boolean to false (searchView.showSearch(false))

**Comment by zunjae** [comment]
That seems to have worked, ty
