### ISSUE TITLE
App Crashes when we open app after some time from background 

### ISSUE THREAD

**Issue by ghost** [Ferfalk/SimpleSearchView#37]
**### Seems Like Issue here**
_https://github.com/Ferfalk/SimpleSearchView/blob/1e62036e69c983b84544f8eee64c4917e2cbb17e/simplesearchview/src/main/java/com/ferfalk/simplesearchview/SimpleSearchView.kt_
When Reading and writing to parcel 
### Stack Trace
 Process: com.doc.scanner.doc.reader.documentscan, PID: 19451
    java.lang.RuntimeException: Parcel android.os.Parcel@5cbf9d2: Unmarshalling unknown type code 6553705 at offset 3092
        at android.os.Parcel.readValue(Parcel.java:3269)
        at android.os.Parcel.readSparseArrayInternal(Parcel.java:3666)
        at android.os.Parcel.readSparseArray(Parcel.java:2808)
        at android.os.Parcel.readValue(Parcel.java:3247)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3583)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:296)
        at android.os.BaseBundle.unparcel(BaseBundle.java:240)
        at android.os.Bundle.getSparseParcelableArray(Bundle.java:1079)
        at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2197)
        at android.app.Activity.onRestoreInstanceState(Activity.java:1743)
        at android.app.Activity.performRestoreInstanceState(Activity.java:1689)
        at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1357)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3760)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:232)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:212)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:184)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2315)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:263)
        at android.app.ActivityThread.main(ActivityThread.java:8276)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
### Request To Admin
Please look at this issue ASAP

**Comment by yustapps** [comment]
Any fix?

**Comment by F-19-F** [comment]
me too

**Comment by F-19-F** [comment]
add  [this](https://github.com/F-19-F/SimpleSearchView/blob/33200f531b4eef4d36917b290ba41c4e247afa4a/simplesearchview/src/main/java/com/ferfalk/simplesearchview/SimpleSearchView.kt#L651)

**Comment by yustapps** [comment]
Any fix for this? I have my production app crashing.

**Comment by F-19-F** [comment]
**>** Any fix for this? I have my production app crashing.


you can use this prebuilt aar 
[here](https://github.com/F-19-F/SimpleSearchView/releases/tag/fix)
copy aar to your app/libs and replace your app’s build.gradle 
`//   implementation 'com.github.Ferfalk:SimpleSearchView:0.2.0'`
 with
 ` implementation files("libs/simplesearchview-release.aar") `

**Comment by yustapps** [comment]
Hi,

I do but I go t this : Error inflating class
com.ferfalk.simplesearchview.SimpleSearchView

**Comment by yustapps** [comment]
Can you help me to fix this problem? I don't know why I am getting error inflating class.

**Comment by artiomcarabash** [comment]
Fixed! 👍  Thanks to @F-19-F
